name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using the latest version of aws-auto-refresh
          required: true
        - label: I have read the [documentation](../README.md)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: The daemon fails to refresh tokens for my profile...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tokens should refresh automatically before expiry
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The daemon logs an error and stops refreshing
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Configure profile with SSO settings
        2. Run `aws-auto-refresh start`
        3. Wait for token to expire
        4. Observe error in logs
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your `~/.aws-auto-refresh/config.json` (remove sensitive data)
      render: json
      placeholder: |
        {
          "profiles": ["my-profile"],
          "refreshBeforeMinutes": 5
        }
    validations:
      required: false

  - type: textarea
    id: aws-config
    attributes:
      label: AWS Configuration
      description: Relevant sections from `~/.aws/config` (remove sensitive data)
      render: ini
      placeholder: |
        [profile my-profile]
        sso_start_url = https://example.awsapps.com/start
        sso_region = us-east-1
        sso_account_id = 123456789012
        sso_role_name = MyRole
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (set `"level": "debug"` for verbose logs)
      render: shell
      placeholder: |
        [2026-02-15 10:30:45] ERROR: Failed to refresh token for profile 'my-profile'
        [2026-02-15 10:30:45] ERROR: Error code: InvalidGrantException
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: aws-auto-refresh Version
      description: Run `npm list aws-auto-refresh` or check `package.json`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: "v18.12.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., macOS 13.1, Ubuntu 22.04, Windows 11
      placeholder: "macOS 13.1"
    validations:
      required: true

  - type: input
    id: aws-cli-version
    attributes:
      label: AWS CLI Version
      description: Run `aws --version`
      placeholder: "aws-cli/2.9.0"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: This started happening after upgrading AWS CLI...
    validations:
      required: false

  - type: checkboxes
    id: security
    attributes:
      label: Security
      description: If this is a security vulnerability, please DO NOT file a public issue
      options:
        - label: This is NOT a security vulnerability (see [SECURITY.md](../SECURITY.md))
          required: true
